insert into assistance (user_id, event_id, puntuation, comentary) values (70, 72, 5, 'tristique in tempus sit amet sem fusce consequat nulla');
insert into assistance (user_id, event_id, puntuation, comentary) values (15, 57, 1, 'platea dictumst etiam faucibus');
insert into assistance (user_id, event_id, puntuation, comentary) values (54, 43, 5, 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum');
insert into assistance (user_id, event_id, puntuation, comentary) values (19, 10, 2, 'ipsum dolor sit amet consectetuer adipiscing elit proin risus');
insert into assistance (user_id, event_id, puntuation, comentary) values (73, 60, 4, 'quam pede lobortis ligula sit amet eleifend pede');
insert into assistance (user_id, event_id, puntuation, comentary) values (92, 9, 5, 'consectetuer eget rutrum');
insert into assistance (user_id, event_id, puntuation, comentary) values (26, 80, 4, 'sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum');
insert into assistance (user_id, event_id, puntuation, comentary) values (48, 92, 1, 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros');
insert into assistance (user_id, event_id, puntuation, comentary) values (2, 22, 4, 'ante ipsum primis in faucibus orci luctus et ultrices');
insert into assistance (user_id, event_id, puntuation, comentary) values (50, 59, 5, 'dolor morbi vel lectus in quam');
insert into assistance (user_id, event_id, puntuation, comentary) values (96, 78, 5, 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris');
insert into assistance (user_id, event_id, puntuation, comentary) values (43, 40, 5, 'tempus semper est quam pharetra magna ac consequat metus sapien');
insert into assistance (user_id, event_id, puntuation, comentary) values (68, 90, 3, 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into assistance (user_id, event_id, puntuation, comentary) values (96, 11, 3, 'consequat morbi a ipsum integer a nibh in quis justo');
insert into assistance (user_id, event_id, puntuation, comentary) values (17, 50, 2, 'id lobortis convallis tortor risus dapibus');
insert into assistance (user_id, event_id, puntuation, comentary) values (39, 33, 5, 'odio elementum eu interdum eu tincidunt in leo maecenas');
insert into assistance (user_id, event_id, puntuation, comentary) values (24, 52, 1, 'non velit nec');
insert into assistance (user_id, event_id, puntuation, comentary) values (99, 75, 5, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate');
insert into assistance (user_id, event_id, puntuation, comentary) values (13, 78, 4, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis');
insert into assistance (user_id, event_id, puntuation, comentary) values (6, 95, 5, 'ipsum primis in faucibus orci luctus et');
insert into assistance (user_id, event_id, puntuation, comentary) values (60, 47, 5, 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit');
insert into assistance (user_id, event_id, puntuation, comentary) values (44, 69, 5, 'felis eu sapien cursus vestibulum');
insert into assistance (user_id, event_id, puntuation, comentary) values (43, 54, 5, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into assistance (user_id, event_id, puntuation, comentary) values (2, 16, 5, 'in tempor turpis nec euismod');
insert into assistance (user_id, event_id, puntuation, comentary) values (50, 34, 2, 'nulla pede ullamcorper augue');
insert into assistance (user_id, event_id, puntuation, comentary) values (29, 1, 5, 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into assistance (user_id, event_id, puntuation, comentary) values (31, 80, 1, 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst');
insert into assistance (user_id, event_id, puntuation, comentary) values (77, 56, 2, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum');
insert into assistance (user_id, event_id, puntuation, comentary) values (74, 21, 1, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus');
insert into assistance (user_id, event_id, puntuation, comentary) values (73, 63, 1, 'massa id nisl venenatis');
insert into assistance (user_id, event_id, puntuation, comentary) values (78, 71, 2, 'vehicula consequat morbi a ipsum integer');
insert into assistance (user_id, event_id, puntuation, comentary) values (13, 29, 2, 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into assistance (user_id, event_id, puntuation, comentary) values (95, 16, 1, 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi');
insert into assistance (user_id, event_id, puntuation, comentary) values (59, 26, 2, 'faucibus orci luctus et ultrices posuere cubilia curae');
insert into assistance (user_id, event_id, puntuation, comentary) values (98, 61, 5, 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into assistance (user_id, event_id, puntuation, comentary) values (73, 11, 3, 'aliquam erat volutpat in congue etiam justo etiam pretium');
insert into assistance (user_id, event_id, puntuation, comentary) values (24, 90, 4, 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis');
insert into assistance (user_id, event_id, puntuation, comentary) values (99, 70, 1, 'venenatis lacinia aenean sit amet justo morbi');
insert into assistance (user_id, event_id, puntuation, comentary) values (5, 94, 5, 'augue vestibulum ante ipsum primis');
insert into assistance (user_id, event_id, puntuation, comentary) values (18, 14, 5, 'condimentum id luctus nec molestie sed justo pellentesque');
insert into assistance (user_id, event_id, puntuation, comentary) values (70, 28, 5, 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque');
insert into assistance (user_id, event_id, puntuation, comentary) values (94, 76, 3, 'nulla pede ullamcorper augue a suscipit nulla elit');
insert into assistance (user_id, event_id, puntuation, comentary) values (47, 88, 5, 'potenti in eleifend quam a');
insert into assistance (user_id, event_id, puntuation, comentary) values (25, 28, 1, 'pede posuere nonummy integer non velit donec diam');
insert into assistance (user_id, event_id, puntuation, comentary) values (91, 9, 1, 'consequat morbi a ipsum integer a nibh in quis');
insert into assistance (user_id, event_id, puntuation, comentary) values (92, 62, 4, 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis est');
insert into assistance (user_id, event_id, puntuation, comentary) values (39, 61, 4, 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into assistance (user_id, event_id, puntuation, comentary) values (3, 10, 5, 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis');
insert into assistance (user_id, event_id, puntuation, comentary) values (85, 61, 4, 'maecenas tristique est et tempus semper est quam pharetra');
insert into assistance (user_id, event_id, puntuation, comentary) values (81, 13, 5, 'eget nunc donec quis orci');
insert into assistance (user_id, event_id, puntuation, comentary) values (47, 77, 1, 'in consequat ut nulla sed accumsan felis');
insert into assistance (user_id, event_id, puntuation, comentary) values (80, 62, 2, 'quisque erat eros viverra');
insert into assistance (user_id, event_id, puntuation, comentary) values (86, 52, 4, 'justo eu massa donec dapibus duis');
insert into assistance (user_id, event_id, puntuation, comentary) values (85, 5, 1, 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non');
insert into assistance (user_id, event_id, puntuation, comentary) values (57, 41, 5, 'accumsan odio curabitur convallis');
insert into assistance (user_id, event_id, puntuation, comentary) values (28, 30, 5, 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus');
insert into assistance (user_id, event_id, puntuation, comentary) values (45, 2, 5, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices');
insert into assistance (user_id, event_id, puntuation, comentary) values (15, 72, 2, 'sed magna at');
insert into assistance (user_id, event_id, puntuation, comentary) values (77, 67, 1, 'pede justo eu massa donec dapibus duis at');
insert into assistance (user_id, event_id, puntuation, comentary) values (11, 3, 4, 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus');
insert into assistance (user_id, event_id, puntuation, comentary) values (93, 50, 1, 'viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper');
insert into assistance (user_id, event_id, puntuation, comentary) values (48, 61, 5, 'justo eu massa donec dapibus duis at velit eu est congue elementum');
insert into assistance (user_id, event_id, puntuation, comentary) values (54, 88, 2, 'cum sociis natoque');
insert into assistance (user_id, event_id, puntuation, comentary) values (8, 22, 2, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into assistance (user_id, event_id, puntuation, comentary) values (54, 9, 3, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula');
insert into assistance (user_id, event_id, puntuation, comentary) values (9, 82, 1, 'vestibulum sed magna at');
insert into assistance (user_id, event_id, puntuation, comentary) values (57, 32, 1, 'suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus');
insert into assistance (user_id, event_id, puntuation, comentary) values (63, 13, 1, 'nec euismod scelerisque quam turpis adipiscing lorem vitae');
insert into assistance (user_id, event_id, puntuation, comentary) values (74, 42, 5, 'non mauris morbi non lectus aliquam sit amet diam');
insert into assistance (user_id, event_id, puntuation, comentary) values (100, 90, 4, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into assistance (user_id, event_id, puntuation, comentary) values (68, 67, 4, 'ipsum primis in faucibus orci luctus et');
insert into assistance (user_id, event_id, puntuation, comentary) values (27, 14, 1, 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien');
insert into assistance (user_id, event_id, puntuation, comentary) values (40, 55, 2, 'rutrum neque aenean auctor gravida sem praesent id massa id');
insert into assistance (user_id, event_id, puntuation, comentary) values (95, 61, 2, 'odio odio elementum eu interdum');
insert into assistance (user_id, event_id, puntuation, comentary) values (61, 10, 2, 'congue risus semper porta volutpat');
insert into assistance (user_id, event_id, puntuation, comentary) values (3, 93, 2, 'in hac habitasse platea dictumst etiam faucibus');
insert into assistance (user_id, event_id, puntuation, comentary) values (94, 36, 3, 'magna vestibulum aliquet ultrices erat tortor sollicitudin');
insert into assistance (user_id, event_id, puntuation, comentary) values (71, 48, 5, 'sapien sapien non mi integer');
insert into assistance (user_id, event_id, puntuation, comentary) values (57, 64, 2, 'massa id nisl venenatis lacinia aenean sit amet');
insert into assistance (user_id, event_id, puntuation, comentary) values (47, 22, 5, 'quam turpis adipiscing lorem vitae mattis nibh ligula nec sem');
insert into assistance (user_id, event_id, puntuation, comentary) values (96, 19, 4, 'convallis eget eleifend');
insert into assistance (user_id, event_id, puntuation, comentary) values (18, 69, 5, 'duis faucibus accumsan odio curabitur convallis duis consequat dui');
insert into assistance (user_id, event_id, puntuation, comentary) values (20, 11, 1, 'varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit');
insert into assistance (user_id, event_id, puntuation, comentary) values (73, 85, 1, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer');
insert into assistance (user_id, event_id, puntuation, comentary) values (81, 80, 4, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into assistance (user_id, event_id, puntuation, comentary) values (82, 93, 3, 'sed augue aliquam erat volutpat');
insert into assistance (user_id, event_id, puntuation, comentary) values (18, 23, 4, 'semper sapien a libero nam dui proin leo');
insert into assistance (user_id, event_id, puntuation, comentary) values (8, 6, 3, 'praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum');
insert into assistance (user_id, event_id, puntuation, comentary) values (62, 11, 4, 'aenean auctor gravida sem');
insert into assistance (user_id, event_id, puntuation, comentary) values (2, 89, 3, 'suspendisse potenti in eleifend quam');
insert into assistance (user_id, event_id, puntuation, comentary) values (1, 48, 2, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi');
insert into assistance (user_id, event_id, puntuation, comentary) values (57, 91, 2, 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero');
insert into assistance (user_id, event_id, puntuation, comentary) values (18, 2, 4, 'dapibus duis at velit eu est');
insert into assistance (user_id, event_id, puntuation, comentary) values (99, 97, 3, 'lacinia aenean sit amet');
insert into assistance (user_id, event_id, puntuation, comentary) values (99, 6, 1, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into assistance (user_id, event_id, puntuation, comentary) values (94, 15, 3, 'hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris');
insert into assistance (user_id, event_id, puntuation, comentary) values (42, 65, 5, 'odio justo sollicitudin ut suscipit a feugiat et');
insert into assistance (user_id, event_id, puntuation, comentary) values (51, 66, 1, 'posuere metus vitae ipsum aliquam non mauris');
insert into assistance (user_id, event_id, puntuation, comentary) values (84, 27, 2, 'pulvinar lobortis est phasellus sit amet erat nulla');
insert into assistance (user_id, event_id, puntuation, comentary) values (39, 31, 4, 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at');
